# Generated by Django 5.2.7 on 2025-10-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnswer',
            new_name='Answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attempt',
            name='percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tf_correct_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False')], max_length=3),
        ),
    ]
