# Generated by Django 5.2.7 on 2025-10-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0002_rename_useranswer_answer_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
