# Generated by Django 5.2.7 on 2025-11-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0003_alter_attempt_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Зображення до питання'),
        ),
    ]
